modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="the_draconite_ore"
version="1.0.0"
displayName="The Draconite Ore"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Hekisa"

[[dependencies.the_draconite_ore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




